name: Cypress Smoke test
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment:
      name: sasuelab
      url: https://www.saucedemo.com
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: navigate to smoke test
        working-directory: ./sauselab
        run: npm i
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run cypresss
        run: npm run cypress:open:sauselab
   
