name: Cypress Smoke test
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment:
      name: sasuelab
      url: https://www.saucedemo.com
    with:
      baseUrl: ${{ github.BASE_URL }}
      userName : "${{ github.PASSWORD }}",
      password : "${{ github.USERNAME }}"
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: navigate to smoke test
        run : cd sauselab
      - name: Install Nodejs
        run: npm ci
      - name: Cypress smoke execute
        run: npm run cypress:open:sauselab
