name: Cypress Smoke test
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Install Nodjs
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Dependencies
        run : |
            cd sauselab
            npm i
      - name : run test 
        run : npm run cypress:open:sauselab
        env:
          CYPRESS_BASEURL: ${{ secrets.BASE_URL }}
      - name: print value 
        run: "CYPRESS_BASEURL"
        
        
