name: Cypress Smoke test
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment:
      name: sasuelab
      url: https://www.saucedemo.com
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: navigate to smoke test
        run : cd sauselab
      - name: Install Nodejs
        run: |
          npm i
          npm run cypress:open:sauselab
        with:
          baseUrl: ${{ github.BASE_URL }}
          userName : "${{ github.PASSWORD }}",
          password : "${{ github.USERNAME }}"

