name: Cypress Smoke test
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: navigate to the working folder
        run: cd sauselab
      - name: Install Nodjs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run : npm i
      - name : run test
        run : nmp run cypress:open:sauselab
        
